---
title: "Data Preprocessing Yellow Taxi"
author: "Jana Choe"
date: "2026-04-28"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(arrow)
library(dplyr)
library(lubridate)
library(janitor)
library(readr)
library(stringr)

files <- c(
  "~/Downloads/yellow_tripdata_2024-11.parquet",
  "~/Downloads/yellow_tripdata_2024-12.parquet",
  "~/Downloads/yellow_tripdata_2025-01.parquet",
  "~/Downloads/yellow_tripdata_2025-02.parquet"
)

# read + combine
taxi_raw <- lapply(files, function(file) {
  
  df <- read_parquet(file) %>%
    clean_names()

  month <- str_extract(file, "\\d{4}-\\d{2}")
  
  # congestion fee doesn't exist for 2024, adding it
  if (!"cbd_congestion_fee" %in% names(df)) {
    df$cbd_congestion_fee <- 0
  }
  
  df$source_month <- month
  
  return(df)
  
  }) %>%
  bind_rows()

#checking 
cat("Total rows:", nrow(taxi_raw), "\n")
glimpse(taxi_raw)

#remaming datetime colums
taxi_clean <- taxi_raw %>%
  rename(
    pickup_datetime = tpep_pickup_datetime,
    dropoff_datetime = tpep_dropoff_datetime
  )

#creating columns we need later

taxi_clean <- taxi_clean %>%
  mutate(
    
    #fizing datetime format into reql time objects
    pickup_datetime = as.POSIXct(pickup_datetime),
    dropoff_datetime = as.POSIXct(dropoff_datetime),
    
    #durations
    duration_minutes = as.numeric(
      difftime(dropoff_datetime, pickup_datetime, units = "mins")
    ),
    
    
    #speed
    avg_speed_mph = trip_distance / (duration_minutes / 60),
    
    #time columns
    pickup_hour = hour(pickup_datetime),
    pickup_dayofweek = wday(pickup_datetime, week_start = 1) - 1,
    pickup_date = as.Date(pickup_datetime),
    
    tip_pct = ifelse(fare_amount > 0, tip_amount / fare_amount, NA),
    
    # flagging when congestion fee occured
    # true if after 2025/01/05
    # 
    post_congestion_fee = pickup_date >= as.Date("2025-01-05"),
    
    # 1 if tipped 0 if not
    tip_binary = ifelse(tip_amount > 0, 1, 0)
  )


```

```{r}
pre_data_clean <- nrow(taxi_clean)

taxi_clean <- taxi_clean %>%
  filter(
    
    #making sure of the timeframe
    pickup_datetime >= as.POSIXct("2024-11-01"),
    pickup_datetime < as.POSIXct("2025-03-01"),
    dropoff_datetime > pickup_datetime,
    
    # removing outliers, nonsensical datas
    duration_minutes >= 1,
    duration_minutes <= 360,
    
    trip_distance > 0,
    trip_distance <= 100,
    avg_speed_mph <= 80,
    
    fare_amount > 0,
    fare_amount <= 500,
    tip_amount >= 0,
    
    passenger_count <= 6 | is.na(passenger_count),
    
    # removing invalid zones
    pu_location_id >= 1,
    pu_location_id <= 263,
    do_location_id >= 1,
    do_location_id <= 263,
    
    payment_type %in% c(1, 2, 3, 4)
  ) %>%
  mutate(
    # if NA or 0 --> 1 passenger (assumptions, but I would say it's pretty safe assumption)
    passenger_count = ifelse(is.na(passenger_count) | passenger_count == 0, 1, passenger_count),
    
    # fixing congestion fee
    cbd_congestion_fee = ifelse(cbd_congestion_fee < 0 | is.na(cbd_congestion_fee), 0, cbd_congestion_fee)
  )

# check
cat("row count: ", nrow(taxi_clean), "\n")
cat("rows removed:", pre_data_clean - nrow(taxi_clean), "\n")
```

```{r}

# drop total amount
taxi_clean <- taxi_clean %>%
  select(
    -total_amount
  )

# save preprocessed files
write_parquet(
  taxi_clean,
  "~/Downloads/yellow_taxi_preprocessed.parquet"
)
```

```{r}
glimpse(taxi_clean)

summary(taxi_clean$tip_amount)
summary(taxi_clean$fare_amount)
summary(taxi_clean$trip_distance)

table(taxi_clean$payment_type)
table(taxi_clean$tip_binary)

cat("row count:", nrow(taxi_clean), "\n")
```